# Generated by Django 5.1.1 on 2025-01-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodetalle',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
