# Generated by Django 5.1.1 on 2025-01-16 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_alter_configalmacen_abreviatura_and_more'),
        ('inventario', '0002_productodetalle_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_detalles', to='configuraciones.configalmacen'),
        ),
        migrations.AlterField(
            model_name='productodetalle',
            name='cantidad_por_presentacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productodetalle',
            name='total_unidades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productodetalle',
            name='unidades_por_presentacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
