# Generated by Django 5.1.1 on 2024-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfigCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfigMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfigPresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Presentación de Producto',
                'verbose_name_plural': 'Presentaciones de Productos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfigProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('encargado', models.CharField(max_length=50)),
                ('telefono_encargado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ConfigUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['orden'],
            },
        ),
    ]
