# Generated by Django 5.1.1 on 2024-10-23 04:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configalmacen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configalmacen',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_almacenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configalmacen',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configalmacen',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_almacenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configalmacen',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configalmacen',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_almacenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configcategoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 23, 4, 18, 52, 477291, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configcategoria',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configcategoria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configcategoria',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configcategoria',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configcategoria',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmarca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 22, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configmarca',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marcas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmarca',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configmarca',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_marcas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmarca',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configmarca',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_marcas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configpresentacionproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configpresentacionproducto',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presentaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configpresentacionproducto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configpresentacionproducto',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_presentaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configpresentacionproducto',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configpresentacionproducto',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_presentaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configproveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configproveedor',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configproveedor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configproveedor',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configproveedor',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configproveedor',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configunidadmedida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configunidadmedida',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unidad_medida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configunidadmedida',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configunidadmedida',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_unidad_medida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configunidadmedida',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configunidadmedida',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_unidad_medida', to=settings.AUTH_USER_MODEL),
        ),
    ]
