# Generated by Django 5.1.1 on 2024-11-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_configalmacen_created_at_configalmacen_created_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configalmacen',
            name='abreviatura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configalmacen',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configcategoria',
            name='abreviatura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configcategoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configmarca',
            name='abreviatura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configmarca',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configpresentacionproducto',
            name='abreviatura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configpresentacionproducto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configproveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='configunidadmedida',
            name='abreviatura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configunidadmedida',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
